module.exports = {
  ADDRESS_CREATED: require('./address-created'),
  ADDRESS_DELETED: require('./address-deleted'),
  ADDRESS_RESTORED: require('./address-restored'),
  ADDRESS_UNVERIFIED: require('./address-unverified'),
  ADDRESS_UPDATED: require('./address-updated'),
  ADDRESS_VERIFIED: require('./address-verified'),
  EMPLOYMENT_CREATED: require('./employment-created'),
  EMPLOYMENT_DELETED: require('./employment-deleted'),
  EMPLOYMENT_RESTORED: require('./employment-restored'),
  EMPLOYMENT_UNVERIFIED: require('./employment-unverified'),
  EMPLOYMENT_UPDATED: require('./employment-updated'),
  EMPLOYMENT_VERIFIED: require('./employment-verified'),
  LEASE_CREATED: require('./lease-created'),
  LEASE_DELETED: require('./lease-deleted'),
  LEASE_RESTORED: require('./lease-updated'),
  LEASE_UPDATED: require('./lease-updated'),
  UPLOAD_CREATED: require('./upload-created'),
  UPLOAD_DELETED: require('./upload-deleted'),
  UPLOAD_RESTORED: require('./upload-restored')
}
