apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emailer
  labels:
    app: emailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailer
  template:
    metadata:
      labels:
        app: emailer
    spec:
      containers:
        - image: us.gcr.io/poplar-178404/emailer:20171013144234_emailer
          imagePullPolicy: Always
          name: emailer
          env:
            - name: AWS_SQS_QUEUE_NAME
              value: emailer
            - name: FROM_EMAIL
              value: '"Poplar" <hello@poplar.co>"'
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: secret-key
