apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-08-23T19:58:14Z
  generation: 1
  labels:
    run: wp
  name: wp
  namespace: default
  resourceVersion: "1521"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/wp
  uid: 663e27dc-883d-11e7-b49f-42010a8e0fd5
spec:
  replicas: 1
  selector:
    matchLabels:
      run: wp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: wp
    spec:
      containers:
      - image: us.gcr.io/poplar-177617/web:latest
        imagePullPolicy: Always
        name: wp
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: gcr.io/cloudsql-docker/gce-proxy:1.09
        name: cloudsql-proxy
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=poplar-177617:us-east4:poplar-mysql-wp=tcp:3306",
                  "-credential_file=/secrets/cloudsql/poplar-e73d6ec9c0da.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-08-23T19:58:14Z
    lastUpdateTime: 2017-08-23T19:58:14Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
