apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A specification of a Let's Encrypt Certificate to manage"
metadata:
  name: "certificate.stable.hightower.com"
versions:
  - name: v1
