web_api:
  build: ./web-api
  ports:
    - "4000:4000"
  environment:
    - DATABASE_DATABASE=sid
    - DATABASE_USERNAME=sid
    - DATABASE_PASSWORD=sid
    - DATABASE_HOST=pg
    - AWS_ACCESS_KEY_ID=key
    - AWS_SECRET_ACCESS_KEY=key
    - AWS_REGION=us-east-1
    - AWS_SQS_URL=sqs
    - AWS_SQS_PORT=4568
    - EMAILER_QUEUE=emailer
    - KNOWLEDGE_BASE_URL=http://knowledge_base:5000
  volumes:
    - ./web-api:/usr/src/app
  volumes_from:
    - web_api_node_modules
  links:
    - knowledge_base
    - pg
    - testpg
    - sqs

web_api_node_modules:
  image: busybox
  volumes:
    - /usr/src/app/node_modules

knowledge_base:
  build: ./knowledge-base
  ports:
    - "5000:5000"
  environment:
    - DATABASE_DATABASE=knowledge_base
    - DATABASE_USERNAME=knowledge_base
    - DATABASE_PASSWORD=knowledge_base
    - DATABASE_HOST=knowledge_base_pg
    - AWS_ACCESS_KEY_ID=key
    - AWS_SECRET_ACCESS_KEY=key
    - AWS_REGION=us-east-1
    - AWS_FAKE_S3_URL=s3
    - AWS_FAKE_S3_PORT=4569
    - UPLOADS_BUCKET=kb-uploads
  volumes:
    - ./knowledge-base:/usr/src/app
  volumes_from:
    - knowledge_base_node_modules
  links:
    - knowledge_base_pg
    - knowledge_base_testpg
    - s3

knowledge_base_node_modules:
  image: busybox
  volumes:
    - /usr/src/app/node_modules

web:
  build: ./web
  ports:
    - "8080:80"

app:
  build: ./app
  ports:
    - "3000:3000"
  volumes:
    - ./app:/usr/src/app
  volumes_from:
    - app_node_modules

app_node_modules:
  image: busybox
  volumes:
    - /usr/src/app/node_modules

emailer:
  build: ./emailer
  volumes:
    - ./emailer:/usr/src/app
  volumes_from:
    - emailer_node_modules
  environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_REGION=us-east-1
    - AWS_SQS_QUEUE_NAME=emailer
    - AWS_SQS_URL=sqs
    - AWS_SQS_PORT=4568
    - FROM_EMAIL=pnagel5@gmail.com
  links:
    - sqs

emailer_node_modules:
  image: busybox
  volumes:
    - /usr/src/app/node_modules

pg:
  image: postgres:9.4.5
  ports:
    - "5433:5432"
  volumes_from:
    - pg-data
  environment:
    - POSTGRES_USER=sid
    - POSTGRES_PASSWORD=sid
    - POSTGRES_DB=sid

knowledge_base_pg:
  image: postgres:9.4.5
  ports:
    - "5434:5432"
  volumes_from:
    - knowledge_base_pg_data
  environment:
    - POSTGRES_USER=knowledge_base
    - POSTGRES_PASSWORD=knowledge_base
    - POSTGRES_DB=knowledge_base

testpg:
  image: postgres:9.4.5
  environment:
    - POSTGRES_USER=sid
    - POSTGRES_PASSWORD=sid
    - POSTGRES_DB=sid_test

knowledge_base_testpg:
  image: postgres:9.4.5
  environment:
    - POSTGRES_USER=knowledge_base
    - POSTGRES_PASSWORD=knowledge_base
    - POSTGRES_DB=knowledge_base_test

pg-data:
  image: busybox
  volumes:
    - "/var/lib/postgresql/data"

knowledge_base_pg_data:
  image: busybox
  volumes:
    - "/var/lib/postgresql/data"

sqs:
  image: airdock/fake-sqs

s3:
  image: lphoward/fake-s3

web:
  build: ./web
  ports:
    - "8080:80"
  environment:
    - WORDPRESS_DB_PASSOWRD=example
    - WORDPRESS_DB_HOST=mariadb
    - WORDPRESS_DB_USER=wordpress
    - WORDPRESS_DB_PASSWORD=wordpress
  links:
    - mariadb

mariadb:
  image: mariadb
  volumes_from:
    - mariadb_data
  environment:
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=wordpress
    - MYSQL_ROOT_PASSWORD=example

mariadb_data:
  image: busybox
  volumes:
    - "/var/lib/mysql"
