web_api:
  build: ./web-api
  ports:
    - "4000:4000"
  environment:
    - DATABASE_DATABASE=sid
    - DATABASE_USERNAME=sid
    - DATABASE_PASSWORD=sid
    - DATABASE_HOST=pg
    - AWS_ACCESS_KEY_ID=key
    - AWS_SECRET_ACCESS_KEY=key
    - AWS_REGION=us-east-1
    - AWS_SQS_URL=sqs
    - AWS_SQS_PORT=4568
  volumes:
    - ./web-api:/usr/src/app
  volumes_from:
    - web_api_node_modules
  links:
    - pg
    - testpg
    - sqs

web_api_node_modules:
  image: busybox
  volumes:
    - /usr/src/app/node_modules

web:
  build: ./web
  ports:
    - "8080:80"

app:
  build: ./app
  ports:
    - "3000:3000"
  volumes:
    - ./app:/usr/src/app
  volumes_from:
    - app_node_modules

app_node_modules:
  image: busybox
  volumes:
    - /usr/src/app/node_modules

pg:
  image: postgres:9.4.5
  ports:
    - "5433:5432"
  volumes_from:
    - pg-data
  environment:
    - POSTGRES_USER=sid
    - POSTGRES_PASSWORD=sid
    - POSTGRES_DB=sid

testpg:
  image: postgres:9.4.5
  environment:
    - POSTGRES_USER=sid
    - POSTGRES_PASSWORD=sid
    - POSTGRES_DB=sid_test

pg-data:
  image: busybox
  volumes:
    - "/var/lib/postgresql/data"

sqs:
  image: airdock/fake-sqs
